version: '3.1'
services:
  db:
    image: postgres:16
    user: root
    environment:
      - POSTGRES_USER=odoo_client
      - POSTGRES_PASSWORD=changemeoryouilldie
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always             # run as a service

  odoo17:
    image: odoo:17
    user: root
    depends_on:
      - db
    ports:
      - "42017:8069"
      - "42018:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo_client
      - PASSWORD=changemeoryouilldie

    restart: always             # run as a service
